### PR TITLE
Add idle timeout, fix read timeout, and improve error handling

### LINKED ISSUE #55: error : ConnectionReset: An existing connection was forcibly closed by the remote host
Using deno_mysql in conjunction with oak for developing CRUD api against MySql db.  Application is able to initiate connection and serve multiple client.execute(getQuery) requests with no problem.  

However, if no requests are undertaken within 10 minute window the next call to client.execute(getQuery) fails, an immediate 2nd call also falls and then on a 3rd call the connection is established and continues to work as normal.

The following error is caught :-

Error: An existing connection was forcibly closed by the remote host. (os error 10054) 
    at SendPacket.send (https://deno.land/x/mysql/src/packets/packet.ts:30:13)
    at async Connection.execute (https://deno.land/x/mysql/src/connection.ts:161:5)
    at async https://deno.land/x/mysql/src/client.ts:101:14
    at async Client.useConnection (https://deno.land/x/mysql/src/client.ts:111:22)
    at async Client.execute (https://deno.land/x/mysql/src/client.ts:100:12)
    at async getCodeLookups (file:///C:/Users/Ian%20Strange%20-%20T1/Documents/GitHub/deno-auth/controllers/codelookup_controller.ts:16:3)
    at async allowedMethods (https://deno.land/x/oak@v5.2.0/router.ts:484:7)
    at async Application.#handleRequest (https://deno.land/x/oak@v5.2.0/application.ts:218:9)

On the 3rd call the client provides INFO messages to show reestablishing of connection 

INFO connecting 127.0.0.1:3306
INFO connected to 127.0.0.1

Have been experiencing this issue without realising the nature of the error for at least 2 weeks - and only today have looked further and discovered the connection issue.

I'm unsure if this an issue with deno_mysql or if its an issue with Deno.Conn.  

Is it possible to config around this? Or does deno_mysql need to change to cope with this timeout event and re-establish connection without error.

Let me know if you need any further info.

### LINKED ISSUE #79: Error on querying after hours of idle
```
Error: Read packet timeout
    at Connection.nextPacket (connection.ts:101:17)
    at async Connection.execute (connection.ts:162:19)
    at async Connection.query (connection.ts:143:20)
    at async client.ts:90:14
    at async Client.useConnection (client.ts:111:22)
    at async Client.query (client.ts:89:12)
    at (my code...)
```

To reproduce:
1) Create a client with connection pool
2) Do a query
3) Wait for more than 8 hours (the default mysql server idle timeout)
4) Query again, get the error

The case is that mysql server disconnect the connection in the pool on idle timeout.
Then we get the disconnected connection from the pool, read from it, and get the EOF.

I suggest to add client-side connection idle timeout, which should shorter than 8 hours by default.

### PR DESCRIPTION
**Pull request by lideming**
Should fix #79, fix #55

### CODE REVIEW

**Comment by lideming** [comment]
Test for this is not easy...

We need to change MySQL / MariaDB configuration file before the test.
Nobody want the test to run for several hours. 😂

**Comment by lideming** [comment]
These test failures are caused by (possible) Deno bug (https://github.com/denoland/deno/issues/7844).

**Comment by manyuanrong** [comment]
awesome!

**Comment by lideming** [comment]
@manyuanrong Thanks!

I am wondering why this PR is merged as a single commit. These commit messages were lost. :see_no_evil:

**Pull request merged**
