### PR TITLE
clientConfig's pool property naming is vague.

### PR DESCRIPTION
**Pull request by magichim**
Hi!
At first, I really thank you for making this project and I learned much from this code.

I am watching your code and comparing with node.js mysql lib.
During analyzing your code, I confused a some naming. This is pool in clientconfig object.

I suggest that change the property name as poolSize. I think It's more clear and helpful to other people. :)

### CODE REVIEW

**Comment by manyuanrong** [comment]
Thank you for PR, but I hope it can pass CI

**Comment by magichim** [comment]
Thank you for reviewing. :) @manyuanrong

**Comment by manyuanrong** [comment]
LGTM

**Comment by manyuanrong** [comment]
LGTM

**Pull request merged**
