### PR TITLE
Update std to 0.63.0

### PR DESCRIPTION
**Pull request by Cat66000**
Hello, I wanted to update std.
Please do not merge until bytes_formater is updated too.

### CODE REVIEW

**Comment by manyuanrong** [comment]
ci failed

**Comment by narwy** [comment]
@manyuanrong This needs updating to std 0.63.0 urgently

**Comment by narwy** [comment]
@manyuanrong This is failing due to the deno version being 1.0.0 and not 1.2.2 please can you update the CI to support the latest version of deno to fix std issues.

**Comment by narwy** [comment]
Can we get the byte formatter put back to deno.land as well please for the cdn

**Comment by manyuanrong** [comment]
#67

**Pull request closed without merging**
